algo_params:
  buffer_size: 200000
  gamma: 0.98
  gradient_steps: -1
  learning_rate: 0.001
  learning_starts: 0
  n_critics: 2
  net_arch:
  - 400
  - 300
  sigma: 0.05
general_params:
  agent: TD3
  env_name: CustomHumanoidStandup-v2
  exp_name: Algo_Exp_NoET
  expert_data_path: demos_data/humanoidStandup/ppoDemo_CustomHumanoidStandup-v2.pkl
  num_episodes: 100
  num_runs: 5
plotter_params:
  dpi: 70
  font_scale: 2.5
  height: 8
  linewidth: 3.5
  max_num_episodes: 100
  smooth_window: 10
  width: 10
tester_params:
  num_episodes: 100
  render: false
